apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: chatbot-rolling-2025040903
  janus-idp.io/tekton: chatbot-rolling-2025040903
  backstage.io/kubernetes-id: chatbot-rolling-2025040903
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: chatbot-rolling-2025040903
resources:
  - application-dev.yaml