apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: chatbot-rolling-2025040903
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-rolling-2025040903
  name: chatbot-rolling-2025040903
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: chatbot-rolling-2025040903
